/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;

/**
 *
 * @author PUTRI
 */
public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Pemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmsPnl = new javax.swing.JPanel();
        pmsLbl = new javax.swing.JLabel();
        tglLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        dcPms = new datechooser.beans.DateChooserCombo();
        simpanBtn = new java.awt.Button();
        batalBtn = new java.awt.Button();
        judulLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        pmsPnl.setBackground(new java.awt.Color(255, 255, 255));
        pmsPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pmsLbl.setText("Id_Pemesanan");
        pmsPnl.add(pmsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 44, -1, -1));

        tglLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tglLbl.setText("Tanggal Pemesanan");
        pmsPnl.add(tglLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 94, -1, -1));

        totalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLbl.setText("Total Pemesanan");
        pmsPnl.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 293, -1, -1));

        tfId.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 41, 427, 35));

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });
        pmsPnl.add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 290, 427, 35));
        pmsPnl.add(dcPms, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 94, 427, 35));

        simpanBtn.setBackground(new java.awt.Color(86, 204, 242));
        simpanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simpanBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simpanBtn.setLabel("Simpan");
        simpanBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(simpanBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        batalBtn.setBackground(new java.awt.Color(86, 204, 242));
        batalBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        batalBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        batalBtn.setLabel("Batal");
        batalBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(batalBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        judulLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLbl.setText("Tambah Detail Pemesanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(judulLbl)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pmsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(judulLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pmsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

    public void setActionListener(ActionListener a){
        simpanBtn.addActionListener(a);
        batalBtn.addActionListener(a);
    }
     
    
    public String getID(){
       String s = tfId.getText();
       return s;
    }
       
    public int getTotal(){
        int i = Integer.parseInt(tfTotal.getText());
        return i;
    }
    
    public String getTglPinjam(){
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("yyyy-MM-dd");
        dcPms.setDateFormat(kal);
        return dcPms.getText();
    }
    
    public Button getBtnSimpan(){
        return simpanBtn;
    }
    
    public Button getBtnBatal(){
        return batalBtn;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button batalBtn;
    private datechooser.beans.DateChooserCombo dcPms;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JLabel pmsLbl;
    private javax.swing.JPanel pmsPnl;
    private java.awt.Button simpanBtn;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JLabel tglLbl;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
