/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author PUTRI
 */
public class DashboardKasir extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public DashboardKasir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ksrPnl = new javax.swing.JPanel();
        kasirLbl = new javax.swing.JLabel();
        jbKeluar = new javax.swing.JButton();
        jbDashboard = new javax.swing.JButton();
        jbPembayaran = new javax.swing.JButton();
        jbPemesanan = new javax.swing.JButton();
        fotoLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        judulLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pesanLbl = new javax.swing.JLabel();
        notifLbl = new javax.swing.JLabel();
        headPnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ksrPnl.setBackground(new java.awt.Color(0, 204, 204));
        ksrPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        ksrPnl.setMinimumSize(new java.awt.Dimension(500, 400));
        ksrPnl.setPreferredSize(new java.awt.Dimension(500, 350));
        ksrPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kasirLbl.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        kasirLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kasirLbl.setText("KASIR");
        ksrPnl.add(kasirLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 180, 220, -1));

        jbKeluar.setBackground(new java.awt.Color(255, 255, 255));
        jbKeluar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbKeluar.setText("Keluar");
        jbKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbKeluarActionPerformed(evt);
            }
        });
        ksrPnl.add(jbKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 230, 50));

        jbDashboard.setBackground(new java.awt.Color(255, 255, 255));
        jbDashboard.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbDashboard.setText("Dashboard");
        jbDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDashboardActionPerformed(evt);
            }
        });
        ksrPnl.add(jbDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 50));

        jbPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        jbPembayaran.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbPembayaran.setText("Data Pembayaran");
        jbPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPembayaranActionPerformed(evt);
            }
        });
        ksrPnl.add(jbPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 50));

        jbPemesanan.setBackground(new java.awt.Color(255, 255, 255));
        jbPemesanan.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jbPemesanan.setText("Detail Pemesanan");
        jbPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPemesananActionPerformed(evt);
            }
        });
        ksrPnl.add(jbPemesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 230, 50));

        fotoLbl.setIcon(new javax.swing.ImageIcon("E:\\files\\Teknik Informatika\\semester 5\\IMPAL\\OO SISFO APOTEK\\Aset\\girll.png")); // NOI18N
        ksrPnl.add(fotoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        idLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idLbl.setText("ID-KSR001");
        ksrPnl.add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 220, 230, -1));

        getContentPane().add(ksrPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 230, 780));

        judulLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLbl.setText("SELAMAT DATANG DI APLIKASI APOTEK SEHAT");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 620, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        menuLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuLbl.setIcon(new javax.swing.ImageIcon("E:\\files\\Teknik Informatika\\semester 5\\IMPAL\\OO SISFO APOTEK\\Aset\\buttonn.png")); // NOI18N
        menuLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menuLbl.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(menuLbl);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, 60));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        pesanLbl.setIcon(new javax.swing.ImageIcon("E:\\files\\Teknik Informatika\\semester 5\\IMPAL\\OO SISFO APOTEK\\Aset\\Pesann.png")); // NOI18N
        jPanel1.add(pesanLbl);

        notifLbl.setIcon(new javax.swing.ImageIcon("E:\\files\\Teknik Informatika\\semester 5\\IMPAL\\OO SISFO APOTEK\\Aset\\Notifikasii.png")); // NOI18N
        notifLbl.setToolTipText("");
        notifLbl.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(notifLbl);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 110, 60));

        headPnl.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(headPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 660, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbKeluarActionPerformed

    private void jbDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDashboardActionPerformed

    private void jbPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPembayaranActionPerformed

    private void jbPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPemesananActionPerformed

    public void setActionListener(ActionListener a){
        jbDashboard.addActionListener(a);
        jbPembayaran.addActionListener(a);
        jbPemesanan.addActionListener(a);
        jbKeluar.addActionListener(a);
    }
    
    public JPanel ksrPnl() {
        return ksrPnl;
    }
    
    public JLabel getKasir() {
        return kasirLbl;
    }
    
    public JLabel getPesan() {
        return pesanLbl;
    }
    
    public JLabel getNotif() {
        return notifLbl;
    }
    
    public JButton getBtnKeluar(){
        return jbKeluar;
    }
    
    public JButton getBtnPembayaran(){
        return jbPembayaran;
    }
     
    public JButton getBtnPemesanan(){
        return jbPemesanan;
    }
     
    public JButton getBtnDasboard(){
        return jbDashboard;
    } 
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DashboardKasir().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fotoLbl;
    private javax.swing.JPanel headPnl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbDashboard;
    private javax.swing.JButton jbKeluar;
    private javax.swing.JButton jbPembayaran;
    private javax.swing.JButton jbPemesanan;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JLabel kasirLbl;
    private javax.swing.JPanel ksrPnl;
    private javax.swing.JLabel menuLbl;
    private javax.swing.JLabel notifLbl;
    private javax.swing.JLabel pesanLbl;
    // End of variables declaration//GEN-END:variables
}
