/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author PUTRI
 */
public class EditDataSuplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public EditDataSuplier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmsPnl = new javax.swing.JPanel();
        NamaLbl = new javax.swing.JLabel();
        alamatLbl = new javax.swing.JLabel();
        tlpLbl = new javax.swing.JLabel();
        tfTlp = new javax.swing.JTextField();
        btnSimpan = new java.awt.Button();
        btnBatal = new java.awt.Button();
        tfId = new javax.swing.JTextField();
        idSupLbl = new javax.swing.JLabel();
        tfAlamat = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        judulLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmsPnl.setBackground(new java.awt.Color(255, 255, 255));
        pmsPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmsPnl.setMinimumSize(new java.awt.Dimension(500, 400));
        pmsPnl.setPreferredSize(new java.awt.Dimension(500, 350));
        pmsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NamaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        NamaLbl.setText("Nama");
        pmsPnl.add(NamaLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        alamatLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alamatLbl.setText("Alamat");
        pmsPnl.add(alamatLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        tlpLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tlpLbl.setText("Telepon");
        pmsPnl.add(tlpLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        tfTlp.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfTlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 460, 35));

        btnSimpan.setBackground(new java.awt.Color(86, 204, 242));
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setLabel("Simpan");
        btnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        btnBatal.setBackground(new java.awt.Color(86, 204, 242));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setLabel("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        tfId.setForeground(new java.awt.Color(204, 204, 204));
        tfId.setText("Default");
        tfId.setMinimumSize(new java.awt.Dimension(6, 30));
        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });
        pmsPnl.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 460, 35));

        idSupLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        idSupLbl.setText("Id_Suplier");
        pmsPnl.add(idSupLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        tfAlamat.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 460, 35));

        tfNama.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 460, 35));

        getContentPane().add(pmsPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 95, 780, 570));

        judulLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judulLbl.setText("Edit Data Suplier");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed
    
    public void setActionListener(ActionListener a){
        btnSimpan.addActionListener(a);
        btnBatal.addActionListener(a);
    }
    
    public Button getBtnSimpan(){
        return btnSimpan;
    }
    
    public Button getBtnBatal(){
        return btnBatal;
    }
    
    public String getID(){
        return tfId.getText();
    }
    
    public String getNama(){
        return tfAlamat.getText();
    }
    
    public String getAlamat(){
        return tfAlamat.getText();
    }
    
    public String getTelepon(){
        return tfTlp.getText();
    }
     
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InputResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InputResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InputResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InputResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InputResepObat().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NamaLbl;
    private javax.swing.JLabel alamatLbl;
    private java.awt.Button btnBatal;
    private java.awt.Button btnSimpan;
    private javax.swing.JLabel idSupLbl;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JPanel pmsPnl;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTlp;
    private javax.swing.JLabel tlpLbl;
    // End of variables declaration//GEN-END:variables
}
