/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextArea;

/**
 *
 * @author PUTRI
 */
public class EditResepObat extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public EditResepObat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmsPnl = new javax.swing.JPanel();
        aptIdLbl = new javax.swing.JLabel();
        tglLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        tfId2 = new javax.swing.JTextField();
        dcPms = new datechooser.beans.DateChooserCombo();
        btnSimpan = new java.awt.Button();
        btnBatal = new java.awt.Button();
        tfId1 = new javax.swing.JTextField();
        rspIdLbl1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDeskripsi = new javax.swing.JTextArea();
        judulLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmsPnl.setBackground(new java.awt.Color(255, 255, 255));
        pmsPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmsPnl.setMinimumSize(new java.awt.Dimension(500, 400));
        pmsPnl.setPreferredSize(new java.awt.Dimension(500, 350));
        pmsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aptIdLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        aptIdLbl.setText("Id_Apoteker");
        pmsPnl.add(aptIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        tglLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tglLbl.setText("Tanggal Resep");
        pmsPnl.add(tglLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        totalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLbl.setText("Deskripsi");
        pmsPnl.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        tfId2.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 460, 35));
        pmsPnl.add(dcPms, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 460, 35));

        btnSimpan.setBackground(new java.awt.Color(86, 204, 242));
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setLabel("Simpan");
        btnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));

        btnBatal.setBackground(new java.awt.Color(86, 204, 242));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setLabel("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        tfId1.setMinimumSize(new java.awt.Dimension(6, 30));
        tfId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfId1ActionPerformed(evt);
            }
        });
        pmsPnl.add(tfId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 460, 35));

        rspIdLbl1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rspIdLbl1.setText("Id_Resep");
        pmsPnl.add(rspIdLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jTDeskripsi.setColumns(20);
        jTDeskripsi.setRows(5);
        jScrollPane1.setViewportView(jTDeskripsi);

        pmsPnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 460, 230));

        getContentPane().add(pmsPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 95, 780, 570));

        judulLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLbl.setText("Edit Resep Obat");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfId1ActionPerformed
    
    public void setActionListener(ActionListener a){
        btnSimpan.addActionListener(a);
        btnBatal.addActionListener(a);
    }
    
    public Button getBtnSimpan(){
        return btnSimpan;
    }
    
    public Button getBtnBatal(){
        return btnBatal;
    }
    
    public String getID(){
        return tfId1.getText();
    }

     public String getTglEditRsp(){
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("yyyy-MM-dd");
        dcPms.setDateFormat(kal);
        return dcPms.getText();
    }
    
    public JTextArea getDeskripsi(){
        return jTDeskripsi;
    }
     
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditResepObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditResepObat().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aptIdLbl;
    private java.awt.Button btnBatal;
    private java.awt.Button btnSimpan;
    private datechooser.beans.DateChooserCombo dcPms;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTDeskripsi;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JPanel pmsPnl;
    private javax.swing.JLabel rspIdLbl1;
    private javax.swing.JTextField tfId1;
    private javax.swing.JTextField tfId2;
    private javax.swing.JLabel tglLbl;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
