/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author PUTRI
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judulLbl = new javax.swing.JLabel();
        tfPassword = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        masukSbgLbl = new javax.swing.JLabel();
        cbUser = new javax.swing.JComboBox<>();
        haloUserLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulLbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        judulLbl.setText("APOTEK SEHAT");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setText("PASSWORD");
        getContentPane().add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 380, 60));

        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setText("USERNAME");
        getContentPane().add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 380, 60));

        btnLogin.setText("LOG IN");
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 380, 40));

        masukSbgLbl.setText("Masuk sebagai");
        getContentPane().add(masukSbgLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, -1, -1));

        cbUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apoteker", "Kasir", "Pendata", "Manager" }));
        getContentPane().add(cbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 70, -1));

        haloUserLbl.setText("HALO USER!");
        getContentPane().add(haloUserLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setActionListener(ActionListener a){
        btnLogin.addActionListener(a);
    }
    
    public JButton getBtnLogin(){
        return btnLogin;
    }
    
    public String getUsername(){
        return tfUsername.getText();
    }
    
    public String getPassword(){
        return tfPassword.getText();
    }
    
   public String getUser(){
        int i = cbUser.getSelectedIndex();
        return cbUser.getItemAt(i);
    }
    
    

    
    
     
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cbUser;
    private javax.swing.JLabel haloUserLbl;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JLabel masukSbgLbl;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
