/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Button;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author PUTRI
 */
public class Pemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    public Pemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmsPnl = new javax.swing.JPanel();
        pmsLbl = new javax.swing.JLabel();
        tglLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        dcPms = new datechooser.beans.DateChooserCombo();
        btnSimpan = new java.awt.Button();
        btnBatal = new java.awt.Button();
        judulLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 236, 236));
        setMaximumSize(new java.awt.Dimension(1280, 1024));
        setPreferredSize(new java.awt.Dimension(767, 548));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmsPnl.setBackground(new java.awt.Color(255, 255, 255));
        pmsPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pmsPnl.setMinimumSize(new java.awt.Dimension(1280, 1024));
        pmsPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pmsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pmsLbl.setText("Id_Pemesanan");
        pmsPnl.add(pmsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 44, -1, -1));

        tglLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tglLbl.setText("Tanggal Pemesanan");
        pmsPnl.add(tglLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 107, -1, -1));

        totalLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalLbl.setText("Total Pemesanan");
        pmsPnl.add(totalLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 293, -1, -1));

        tfId.setMinimumSize(new java.awt.Dimension(6, 30));
        pmsPnl.add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 41, 427, 35));

        tfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTotalActionPerformed(evt);
            }
        });
        pmsPnl.add(tfTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 290, 427, 35));
        pmsPnl.add(dcPms, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 94, 427, 35));

        btnSimpan.setBackground(new java.awt.Color(86, 204, 242));
        btnSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSimpan.setLabel("Simpan");
        btnSimpan.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        btnBatal.setBackground(new java.awt.Color(86, 204, 242));
        btnBatal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBatal.setLabel("Batal");
        btnBatal.setPreferredSize(new java.awt.Dimension(100, 30));
        pmsPnl.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        getContentPane().add(pmsPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 95, 670, 390));

        judulLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judulLbl.setText("Tambah Detail Pemesanan");
        getContentPane().add(judulLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 48, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTotalActionPerformed

     public void setActionListener(ActionListener a){
        btnSimpan.addActionListener(a);
        btnBatal.addActionListener(a);
    }
    
    public Button getBtnSimpan(){
        return btnSimpan;
    }
    
    public Button getBtnBatal(){
        return btnBatal;
    }
    
    public String getID(){
        return tfId.getText();
    }

     public String getTglPesan(){
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat ("yyyy-MM-dd");
        dcPms.setDateFormat(kal);
        return dcPms.getText();
    }
    
    public int getTotal(){
        int i = Integer.parseInt(tfTotal.getText());
        return i;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBatal;
    private java.awt.Button btnSimpan;
    private datechooser.beans.DateChooserCombo dcPms;
    private javax.swing.JLabel judulLbl;
    private javax.swing.JLabel pmsLbl;
    private javax.swing.JPanel pmsPnl;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JLabel tglLbl;
    private javax.swing.JLabel totalLbl;
    // End of variables declaration//GEN-END:variables
}
